export const TAOBAO_SELECTORS = {
  LOGIN: {
    QR_CODE: '.qrcode-img',
    LOGIN_SUCCESS: '.site-nav-user',
    LOGIN_PAGE: 'https://login.taobao.com/member/login.jhtml',
  },
  ORDERS: {
    PAGE: 'https://buyertrade.taobao.com/trade/itemlist/list_bought_items.htm',
    ORDER_CARD: '.bought-wrapper .bought-list .order-card',
    PRODUCT_NAME: '.product-name a',
    PRODUCT_URL: '.product-name a',
    PRODUCT_IMAGE: '.product-img img',
    PRICE: '.price',
    ORDER_ID: '.order-num',
    PURCHASE_DATE: '.create-time',
    NEXT_PAGE: '.pagination-next',
  },
  ORDER_DETAIL: {
    REBUY_SELECTORS: [
      '[class*="buy-again"]',
      '[class*="buyagain"]',
      '[class*="rebuy"]',
      '[class*="reBuy"]',
      '[class*="repurchase"]',
      '[class*="rePurchase"]',
      '[class*="again"]',
      '[data-spm*="again"]',
      '[data-spm*="rebuy"]',
      '[data-spm*="buy"]',
      '.order-detail a[href*="cart"]',
      '.order-detail a[href*="buy"]',
      '.trade-detail a[href*="cart"]',
      '.trade-detail a[href*="buy"]',
    ],
  },
  CART: {
    URL: 'https://cart.taobao.com/cart.htm',
    SUBMIT_BUTTON: '.submit-btn',
    CHECKOUT_SELECTORS: [
      '.submit-btn',
      '[class*="submit"]',
      '[class*="checkout"]',
      '[class*="settle"]',
      '[class*="j_GO"]',
      '#J_Go',
      '.go-btn',
      '[data-spm*="checkout"]',
      '[data-spm*="settle"]',
    ],
  },
  CHECKOUT: {
    SUBMIT_ORDER: '.submitOrder-btn',
    SUBMIT_ORDER_SELECTORS: [
      '.submitOrder-btn',
      '[class*="submitOrder"]',
      '[class*="submit-order"]',
      '[class*="goPay"]',
      '[class*="go-pay"]',
      '[class*="j_submitOrder"]',
      '#submitOrder',
      '.go-btn',
    ],
    PAY_PASSWORD_FREE: '.password-free-pay',
    CONFIRM_PAY: '.confirm-pay-btn',
  },
} as const
